---
- hosts: host
  roles:
    - role: nftables
      nft_mode: host
  tasks:
    - name: host - add route to public network via gw
      shell: "ip route replace 192.168.1.0/24 via 192.168.2.102"
      changed_when: false

- hosts: gw
  roles:
    - role: nftables
      nft_mode: router

- hosts: all
  tasks:
    - name: install pip
      package: name=python-pip state=present

    - name: install test dependencies
      pip: "name={{ item }}"
      with_items:
        - scapy
        - pytest

- hosts: testrunner
  tasks:
    - name: testrunner - add route to host in private network via gw
      shell: "ip route replace 192.168.2.0/24 via 192.168.1.102"
      changed_when: false

    - name: copy testrunner tests
      copy:
        src: test_runner.py
        dest: /tmp/test_runner.py

    - name: run testrunner tests
      shell: pytest
      args:
        chdir: /tmp
      changed_when: false
      register: testrunner_tests

    - name: display testrunner output
      debug: var=testrunner_tests.stdout_lines
