---
# Variable setup
- name: include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
- name: define nft_package
  set_fact:
    nft_package: "{{ __nft_package }}"
  when: nft_package is not defined

# Setup/install tasks
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure configuration directory exists
  file:
    path: "{{ nft_config_dir }}"
    state: directory
    mode: 0750

- name: set variables
  set_fact:
    _nft_if_external: "{{ nft_if_external | join(', ', attribute='device') }}"

- name: nftables master configuration
  template:
    src: nftables.conf.j2
    dest: "{{ nft_master_config }}"
    mode: 0550
  notify: restart nftables

- name: nftables variables
  template:
    src: vars.j2
    dest: "{{ nft_config_dir }}/vars"
    mode: 0660
  notify: restart nftables

- name: nftables configuration files
  template:
    src: "{{ item }}"
    dest: "{{ nft_config_dir }}/{{ item | regex_replace('.j2','') }}"
    mode: 0440
  with_items: "{{ nft_configuration_files }}"
  notify: restart nftables

- name: ensure nftables is running and enabled on boot
  service: "name=nftables state=started enabled=yes"
